jdbc:
  driverClassName: com.mysql.jdbc.Driver
  jdbc.url: jdbc:mysql://localhost:3306/test-yaml
  jdbc.username: root
  jdbc.password: root

#æ¿?æ´»å…¶ä»–çš„ymlé…ç½®æ–‡ä»¶
spring:
  profiles:
    active: itcast,itheima